spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3307/springuserdb
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: 'true'

management:
  endpoints:
    web:
      exposure:
        include: "*"